#!/usr/bin/env python3
"""Build the FR-003-CON-1 legacy-manifest fixture from the shipped manifest.

The fixture is this module's manifest with the `semantic` block and every
`data_schema` removed: the manifest a consumer that predates the semantic
contract would see. Generating it rather than hand-maintaining it is what makes
the compatibility check real — a hand-written copy drifts, and a drifted copy
proves compatibility with a manifest nobody ships.

    poetry run python scripts/build_legacy_manifest.py           # rewrite
    poetry run python scripts/build_legacy_manifest.py --check    # fail on drift
"""

from __future__ import annotations

import argparse
import copy
import pathlib
import sys

import yaml

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "spec_artifacts_app" / "manifest.yaml"
FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "manifest-legacy.yaml"

HEADER = """# The shipped manifest with the `semantic` block and every `data_schema`
# removed — the manifest a consumer that predates the semantic contract sees.
#
# FR-003-CON-1: adding the block adds no required key anywhere, so this fixture
# must validate under the same FR-035 schema and load with the same artifact
# types. GENERATED by `scripts/build_legacy_manifest.py`; edit that script, not
# this file.
"""


def build() -> str:
    manifest = yaml.safe_load(MANIFEST_PATH.read_text())
    legacy = copy.deepcopy(manifest)
    legacy.pop("semantic", None)
    for entry in legacy["artifact_types"]:
        entry.pop("data_schema", None)
    return HEADER + yaml.safe_dump(legacy, sort_keys=False, width=100)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail on drift; write nothing"
    )
    args = parser.parse_args()

    text = build()
    if args.check:
        current = FIXTURE_PATH.read_text() if FIXTURE_PATH.exists() else None
        if current != text:
            print(
                f"{FIXTURE_PATH.relative_to(REPO_ROOT)} differs from the manifest "
                "it is derived from; run `make schemas` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(
            "legacy-manifest check: "
            f"{FIXTURE_PATH.relative_to(REPO_ROOT)} matches the manifest"
        )
        return 0
    FIXTURE_PATH.write_text(text)
    print(f"legacy manifest: wrote {FIXTURE_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
